# Generated by Django 6.0.3 on 2026-03-30 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["order"],
            },
        ),
        migrations.RemoveField(
            model_name="project",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="project",
            name="live_url",
        ),
        migrations.RemoveField(
            model_name="project",
            name="repo_url",
        ),
        migrations.RemoveField(
            model_name="project",
            name="thumbnail",
        ),
        migrations.AddField(
            model_name="project",
            name="date_range",
            field=models.CharField(
                default=1, help_text="e.g. Nov 2025 - present", max_length=100
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="logo",
            field=models.ImageField(default=1, upload_to="projects/logos/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="mockup",
            field=models.ImageField(blank=True, upload_to="projects/mockups/"),
        ),
        migrations.AddField(
            model_name="project",
            name="points",
            field=models.JSONField(
                default=list, help_text="Enter as a list of strings"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="role",
            field=models.CharField(
                default=1, help_text="e.g. Fullstack Developer - RunAm", max_length=200
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="projects.category",
            ),
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
