# Generated by Django 6.0.3 on 2026-03-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_techstack"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="github_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="technologies",
            field=models.ManyToManyField(blank=True, to="projects.techstack"),
        ),
    ]
