# Generated by Django 6.0.3 on 2026-06-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_github_link_project_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_repo_id',
            field=models.BigIntegerField(blank=True, help_text="GitHub's stable repo id; links this project to a repo across renames.", null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_github_managed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, help_text='Live demo / homepage URL'),
        ),
        migrations.AddField(
            model_name='project',
            name='published',
            field=models.BooleanField(default=True, help_text='Unpublished projects are hidden from the public site. GitHub-synced projects start unpublished until you finish them.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_range',
            field=models.CharField(blank=True, help_text='e.g. Nov 2025 - present', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, upload_to='projects/logos/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, help_text='e.g. Fullstack Developer - RunAm', max_length=200),
        ),
        migrations.AlterField(
            model_name='techstack',
            name='image',
            field=models.ImageField(blank=True, upload_to='tech_stack/'),
        ),
    ]
