# Generated by Django 6.0.3 on 2026-07-09 12:49

import apps.core.imagefields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_github_repo_id_project_is_github_managed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=apps.core.imagefields.CompressedImageField(blank=True, upload_to='projects/logos/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='mockup',
            field=apps.core.imagefields.CompressedImageField(blank=True, upload_to='projects/mockups/'),
        ),
        migrations.AlterField(
            model_name='techstack',
            name='image',
            field=apps.core.imagefields.CompressedImageField(blank=True, upload_to='tech_stack/'),
        ),
    ]
