# Generated by Django 6.0.3 on 2026-07-13 07:14

import apps.core.imagefields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_logo_alter_project_mockup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='techstack',
            name='icon_url',
            field=models.URLField(blank=True, help_text='Auto-filled from Devicon by name on save. Clear it + upload an image to override.', max_length=500),
        ),
        migrations.AlterField(
            model_name='techstack',
            name='image',
            field=apps.core.imagefields.CompressedImageField(blank=True, help_text='Optional manual override (used when Devicon has no logo, or the wrong one).', upload_to='tech_stack/'),
        ),
    ]
