run:
	py manage.py runserver 8080

css:
	npm run dev

build:
	npm run build

migrate:
	py manage.py makemigrations && py manage.py migrate

superuser:
	py manage.py createsuperuser

shell:
	py manage.py shell

collect:
	py manage.py collectstatic --noinput

install:
	pip install -r requirements.txt && npm install
