run:
	python manage.py runserver 8080

css:
	npm run dev

build:
	npm run build

migrate:
	python manage.py makemigrations && python manage.py migrate

superuser:
	python manage.py createsuperuser

shell:
	python manage.py shell

collect:
	python manage.py collectstatic --noinput

install:
	pip install -r requirements.txt && npm install
