# Generated by Django 6.0.3 on 2026-04-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="email",
            field=models.EmailField(default="noemail@example.com", max_length=254),
        ),
        migrations.AddField(
            model_name="feedback",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="feedback/"),
        ),
        migrations.AddField(
            model_name="feedback",
            name="name",
            field=models.CharField(default="Anonymous", max_length=100),
        ),
    ]
