# Generated by Django 6.0.3 on 2026-04-13 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_feedback_email_feedback_image_feedback_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="education/")),
                ("order", models.IntegerField(default=0)),
                (
                    "education",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="core.education",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Education Gallery Items",
                "ordering": ["order"],
            },
        ),
    ]
