# Generated by Django 6.0.3 on 2026-06-27 18:21

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_educationgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='CV', help_text='Internal label, e.g. "CV 2026".', max_length=100)),
                ('file', models.FileField(help_text='Upload a PDF. Replaces the current downloadable CV.', storage=apps.core.models.cv_file_storage, upload_to='cv/')),
                ('is_active', models.BooleanField(default=True, help_text='The CV offered for download on the site.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resume / CV',
                'verbose_name_plural': 'Resume / CV',
                'ordering': ['-updated_at'],
            },
        ),
    ]
