# Generated by Django 6.0.3 on 2026-07-07 09:13

import apps.core.imagefields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationgallery',
            name='image',
            field=apps.core.imagefields.CompressedImageField(upload_to='education/'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=apps.core.imagefields.CompressedImageField(blank=True, null=True, upload_to='feedback/'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=apps.core.imagefields.CompressedImageField(upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=apps.core.imagefields.CompressedImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=apps.core.imagefields.CompressedImageField(upload_to='skills/'),
        ),
    ]
