# Generated by Django 6.0.3 on 2026-07-10 07:07

import apps.core.imagefields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_educationgallery_image_alter_feedback_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='skill',
            name='icon_url',
            field=models.URLField(blank=True, help_text='CDN URL of the Devicon SVG.', max_length=500),
        ),
        migrations.AddField(
            model_name='skill',
            name='slug',
            field=models.SlugField(blank=True, help_text='Devicon slug, e.g. "django". Set by the catalog picker.', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='variant',
            field=models.CharField(blank=True, help_text='Devicon SVG variant, e.g. "original" or "plain".', max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=apps.core.imagefields.CompressedImageField(blank=True, help_text='Only needed when this skill is not from the catalog.', upload_to='skills/'),
        ),
    ]
